version: 0.1.0.1
description: Please see the readme on Github at <https://github.com/tek/polysemy-resume>
license: BSD-2-Clause-Patent
author: Torsten Schmits
maintainer: tek@tryp.io
copyright: 2020 Torsten Schmits
category: Experimental
build-type: Simple
extra-source-files:
  - readme.md
  - changelog.md
